name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        export PYTHONPATH=$PYTHONPATH:.
        python -m pip install --upgrade pip
        pip install pylint==2.4.4
        pip install scipy==1.7.3
        pip install numpy==1.24.4
        pip install pandas==1.4.0
        pip install pytz==2023.3
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
